# CODACY_PROJECT_TOKEN
env:
  - secure: "O0lebAQ8hn4ok/s5K2Nvyvd2NvWa5u7cZa1/rH6weIxPg7/uCFMbJXoUOUcVginuLR83k+CBwSAaE/lNdGRHXEY1+Xoukp/ybqKW+A+2Vie/9MikoRPEAmtM0BpMcDTA+tZcDxIFEdsO6dpqvBMHqVvIPs+pB1M692P3K2dZPsi3u9goq/J4IAL6AIcsroPDKoq9UarxW40Vl6DyYkg03kxVL1I7SCZ0Qlt4HfLS/x/7k2bqs9nkwqDtFq4jpm9euFr5O1hgTnAJ89JpNarufqXSN1GKUoPcyOVK23QFThK4TofmiajqxmF6cSrnIi7CTez2Z5CJYBNtH64DlAvLihjkzVTr3ZMq7sqx57AtHzYrN4SYY8McrFltnI6Ui7ZPSHVfz72s2GugjgJzAUOVPS2JAbjBE5E+Tokt+1mNPdIfFyfhytAAh9WN3MEIuo2el6nx3bk2dWni2hNat+qqQttBCfp6MzlzT5FMffUY7O30iSvWP82SFqAmeo8zMOBPltXGTAWVMmrbJX+ltAktvEzrooP5y6Mr+YzNCEUE0xwkqedMt4H/rgLLeU0XUEs1F08WFYU1sf0WHD3qYclZMQl0WkETbj+3DOhZ40tDC9C3FyP55hFh7oai0h8EcWpBFas4qvlDOnZ0d34OEZbbj44VLRowEGU8JEL9YHBNAes="

language: java
before_install:
  - sudo apt-get install jq
  - wget -O ~/codacy-coverage-reporter-assembly-latest.jar $(curl https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest | jq -r .assets[0].browser_download_url)
install: mvn install -DskipTests -Dgpg.skip
script: mvn -B verify
after_success: java -cp ~/codacy-coverage-reporter-assembly-latest.jar com.codacy.CodacyCoverageReporter -l Java -r aggregate/target/site/jacoco-aggregate/jacoco.xml
